z3/src/ast.rs, z3/src/optimize.rs, z3/src/sort.rs, z3/tests/lib.rs
z3.rs doesn't actually own the memory, but wrapping it in a CString will
assume it does and drop the content (and thus free it) when going out of scope.
The new test will crash with a SIGSEGV on the old code.
=> Handle strings returned from Z3 as borrowed.

z3/src/solver.rs
We don't own the string returned by Z3_solver_to_string(). Using CString causes a move and subsequent double free, resulting in a segfault. This commit changed fmt() to use a CStr like in Ast.
=> Don't move the output of Z3_solver_to_string()

z3/tests/lib.rs
Z3 4.8.1 returned `x=true, y=false`, whereas Z3 4.8.3 and 4.8.4 return
`x=false, y=true`.  Both models are valid but the assertion `xv > yv`
selects only for the former.
=> z3: tests: Fix test_pb_ops_model for Z3 >= 4.8.3

z3/src/ast.rs, z3/src/solver.rs, z3/tests/lib.rs
High-level API support for `Z3_translate` operation.
Usage example can be found in the corresponding unit test.
=> Add API support for AST translate.

z3/src/ast.rs
=> check for empty bounds in forall_const

z3/src/ast.rs, z3/tests/lib.rs
Unless I'm missing something, the high-level bindings have no simple way to create bitvector constants.  This PR adds new functions `Ast::bitvector_from_i64()` and `Ast::bitvector_from_u64()` to mirror the existing `Ast::from_i64` and `Ast::from_u64()` which produce integer constants.  Also adds a test using the new functions (actually, no existing tests used bitvectors at all).
Happy to take feedback on anything - function names, function arguments, anything else.  I'm fairly new here.
All the tests in `tests/lib.rs` still pass with this patch.
=> Create bitvectors from constants

z3/src/ast.rs, z3/src/context.rs, z3/src/func_decl.rs, z3/src/lib.rs, z3/src/model.rs, z3/src/optimize.rs, z3/src/solver.rs, z3/src/sort.rs, z3/tests/lib.rs, z3/tests/semver_tests.rs
This is a first effort to try to address #31.  Comments or code review very welcome.
There are a number of questions or ambiguities, which I've called out in code comments for now (and can remove once the questions are resolved).  For instance, with AST subtypes, I think it makes sense to remove (or at least deprecate) the generic `ctx.named_const()`, `ctx.fresh_const()`, etc methods in favor of the typed variants `ctx.named_bool_const()`, `ctx.named_int_const`, etc; but I'm not sure how important the generic variants are or how breaking that would be.
The first commit in this PR exposes a few additional functions in the high-level API that were previously only in `z3-sys`.  In particular, this means the `SortKind` enum is now a public part of the `z3` crate.  I'm assuming that's OK, but …
=> AST subtypes

z3/src/ast.rs
Rather than only implement `Display` on the various AST subtypes, I thought we might as well also implement `Debug`.  For now, `Debug` just uses the same text representation as `Display` does.
=> impl Debug for Asts

z3/src/ast.rs
These bindings already existed in `z3_sys`, this just adds them to `z3`.
Also reordered a couple `BV` methods to an order that makes more sense to me.
=> Add extract(), sign_ext(), and zero_ext(); document the other BV methods

z3/src/ast.rs, z3/src/context.rs, z3/src/func_decl.rs, z3/src/lib.rs, z3/src/sort.rs, z3/src/symbol.rs, z3/tests/lib.rs
Instead of having to pass a context reference and create an
actual symbol, just pass the data for the symbol and let the
function that needs a symbol create it using Symbol::as_z3_symbol().
=> Simplify Symbols.

z3/Cargo.toml, z3/src/ast.rs, z3/src/config.rs, z3/src/context.rs, z3/src/func_decl.rs, z3/src/lib.rs, z3/src/model.rs, z3/src/optimize.rs, z3/src/solver.rs, z3/src/sort.rs
All bindings types contain raw pointers. Types with raw pointers are not Send (https://doc.rust-lang.org/nomicon/send-and-sync.html). So bindings types cannot be send to other threads. Hence we don't need a global lock.
=> remove Z3_MUTEX

z3/src/ast.rs, z3/src/lib.rs, z3/src/sort.rs
Fixes #42.
The function `Ast::get_sort()` was constructing a `Sort` without doing `Z3_inc_ref` on the underlying Z3 sort object. Rather than just add the `Z3_inc_ref`, I refactored how `Sort` objects are constructed in order to hopefully avoid the problem in the future (and also reduce code duplication in sort.rs).  
While doing this, I discovered that `Sort::uninterpreted()` seemed to have a similar problem, so this PR makes sure that that function also properly performs `Z3_inc_ref` when constructing its `Sort`.
Finally, I added notes in `lib.rs` to hopefully help future developers avoid similar mistakes in the future.
=> Bugfix for Sort refcounting

z3/src/ast.rs
Add a binding for `Z3_simplify()`, which previously was exposed in `z3_sys` but not `z3`.  This operation applies to all `Ast`s.
=> Add a binding for Z3_simplify()

z3/src/ast.rs, z3/src/datatype_builder.rs, z3/src/func_decl.rs, z3/src/lib.rs, z3/src/sort.rs
This creates a way to construct and use Z3 datatypes, which are like Rust enums. There is no support yet for recursive datatypes. Also, accesses are by index and hence a bit unwieldy, but it works.
I don't see a way to emulate Python's nice API in Rust, maybe we can improve on this in the future.
=> Add datatype variant of Ast and a builder

README.md
It seemed like a good idea to me to have links here to the `z3` and `z3-sys` readmes.
Unrelatedly - what remains on the todo list before we get the next crates.io release of `z3`?
=> add more links to the top-level README

z3/src/lib.rs, z3/src/params.rs, z3/src/solver.rs, z3/tests/lib.rs
I needed to set a parameter of the solver, so I added the `Params` structure and a `set_params` method to `Solver`.
Please double check the mutex and `unsafe` blocks before merging, because it's the first time that I use `z3_sys`.
=> Add solver parameters

z3/src/ast.rs, z3/tests/lib.rs
This PR adds a `substitute` method on the `Ast` trait with a default implementation. It just uses the `Z3_substitute` binding from `z3-sys` to do the actual substitution.
A unit test case was also added :) I will be happy to make additional changes based on maintainers' opinion.
=> implemented substitutions for Ast

z3/src/ast.rs, z3/src/lib.rs
Cleans up some equality checks in ast.rs, and also allows external crate users to check whether `Context`s are equal (currently only in-crate users are able to do this).  Also adds some other potentially useful traits that can be straightforwardly derived.
=> Derive PartialEq, Eq, etc on Context and Symbol

z3/src/ast.rs
The naming `new_const` for the default `Array` constructor is unfortunately misleading here, but follows the Z3 convention as well as the pattern set by the other `Ast`s.  So I left that name alone and named the new binding `const_array`.  The result is `Array::const_array()` which is a little redundant.  I'm open to other suggestions.
I also added doc comments to both methods to hopefully help alleviate the confusion.
=> Add a safe binding for z3-sys's Z3_mk_const_array

z3/src/solver.rs
This might be useful when we need to `assert` and make `ast` objects at the same time, like when doing symbolic execution. With this method, we can pass down `solver` as a parameter only but not pass down `context` simultaneously, thus making interfaces cleaner.
=> Feat: Add method get_ctx() to Solver

z3/src/ast.rs
Z3 (in debug mode) will log leaked ASTs by id, so including the id in our own debug logging is helpful for aligning them together.
=> Also log the AST id when creating/cloning/dropping ASTs

z3/src/datatype_builder.rs, z3/tests/lib.rs
We need to destroy the `Z3_constructor` after we've created the constructor function decl, tester function decl, and accessor function decls.
=> Don't leak Z3 custom datatype sort constructors

z3/README.md
First, I just want to say thanks for this crate 🎉🎉🎉
After adding the `z3 = "0.5.0"` dep to my `cargo.toml` file I was getting the following error on `cargo build`:
>linking with `cc` failed: exit code: 1
>... note: ld: library not found for -lz3
It wasn't immediately apparent to me that having to install the underlying Z3 library is a requirement for this crate.
This PR updates the readme to clarify that dependency, and help get folks up and running.
=> Include a note about static-link-z3

z3/src/solver.rs
This PR makes the debugging output a bit more helpful for library users.
Fix #77.
=> Add debug! for Solver::assert and assert_and_track

z3/src/ast.rs, z3/src/sort.rs, z3/tests/lib.rs
This adds bindings to existing Z3 `String` sort, and an AST mapping for it. The code is largely based off the existing bindings. 
Let me know if there are any issues
=> Add String sort and AST type 

z3-sys/build.rs
The static library is quite large, ~250mb in my debug build.
This will help our CI a little bit where we cache build artifacts for faster incremental builds.
=> Rename static lib instead of copy

z3/src/lib.rs, z3/src/ops.rs, z3/tests/ops.rs
this pr adds a lot of macros to implement various traits for datatypes
1. `BV`: Add, Sub, Mul, BitAnd, BitOr, BitXor, Shl, Not, Neg
implementations:
```rust
impl<'a, 'ctx> Add<&'a BV<'ctx>> for BV<'ctx> {}
impl<'a, 'ctx> Add<&'a BV<'ctx>> for &'a BV<'ctx> {}
impl<'a, 'ctx> Add<&'a BV<'ctx>> for u64 {}
impl<'a, 'ctx> Add<&'a BV<'ctx>> for i64 {}
impl<'a, 'ctx> Add<BV<'ctx>> for BV<'ctx> {}
impl<'a, 'ctx> Add<BV<'ctx>> for &'a BV<'ctx> {}
impl<'a, 'ctx> Add<BV<'ctx>> for u64 {}
impl<'a, 'ctx> Add<BV<'ctx>> for i64 {}
impl<'a, 'ctx> Add<i64> for BV<'ctx> {}
impl<'a, 'ctx> Add<i64> for &'a BV<'ctx> {}
impl<'a, 'ctx> Add<u64> for BV<'ctx> {}
impl<'a, 'ctx> Add<u64> for &'a BV<'ctx> {}
impl<'a, 'ctx> AddAssign<&'a BV<'ctx>> for BV<'ctx> {}
impl<'a, 'ctx> AddAssign<BV<'ctx>> for BV<'ctx> {} …
```
=> add std::ops implementations for BV, Int, Real and Bool

z3/src/ast.rs
`Datatype::translate()` is missing mutex acquisition before calling `Z3_translate()`
=> [Fix] acquire mutex before translating Datatype

z3/src/ast.rs, z3/src/context.rs, z3/src/lib.rs, z3/src/model.rs, z3/src/optimize.rs, z3/src/solver.rs, z3/src/sort.rs, z3/tests/lib.rs, z3/tests/semver_tests.rs
In other language bindings, after constructing the context the error handler is set to null/a noop. This should fix #69 .
In the C++ bindings, null is passed.
https://github.com/Z3Prover/z3/blob/141edef0d64796fd387ec2f8efe796a7329c48e2/src/api/c%2B%2B/z3%2B%2B.h#L167
In the ML, Python, and C# bindings, a pointer to a noop function are
passed instead, to the same effect.
https://github.com/Z3Prover/z3/blob/141edef0d64796fd387ec2f8efe796a7329c48e2/src/api/ml/z3native_stubs.c.pre#L448
https://github.com/Z3Prover/z3/blob/141edef0d64796fd387ec2f8efe796a7329c48e2/src/api/python/z3/z3.py#L187
https://github.com/Z3Prover/z3/blob/141edef0d64796fd387ec2f8efe796a7329c48e2/src/api/dotnet/Context.cs#L4627
=> Set the default error handler to None

z3-sys/build.rs
Apparently Fedora will use `lib64` instead of `lib` in some circumstances. This commit should fix the `static-link-z3` build for Fedora.
@julian-seward1, could you try pulling this branch and verifying that it fixes the build issues you are seeing? I'd add a CI job, but github only supports ubuntu. Thanks!
Fixes #98
=> z3-sys: Add Fedora's `lib64` path to rustc's lib search path

z3/src/ast.rs
The same as #80
Currently, the distinct function gets called on the first value with the remaining values as a parameter. This is a very awkward syntax and now even inconsistent compared to other methods
=> Improve function signature of distinct for better ergonomics and consistency

z3/src/ast.rs
This brings support for sets that are empty by default, which is the suggested implementation for a question on StackOverflow: https://stackoverflow.com/questions/16100616/defining-set-in-z3
=> support empty set initialization

z3/src/ast.rs, z3/tests/lib.rs
Adding type parameters to these methods makes it possible to pass non-dynamic ast nodes. It can't be done for slice-accepting methods since those arguments *do* need to be dynamic.
Unfortunately, this is a breaking change that would require a version upgrade -- previous calls to these methods with an into() will fail to compile:
```
type annotations needed
cannot infer type for type parameter `A` declared on the function `forall_const`
note: cannot satisfy `_: z3::ast::Ast<'_>`
help: consider specifying the type arguments in the function call: `::<'ctx, A>`rustc(E0283)
lib.rs(301, 18): cannot infer type for type parameter `A` declared on the function `forall_const`
lib.rs(301, 70): this method call resolves to `T`
ast.rs(1477, 8): required by this bound in `z3::ast::forall_const`
```
So …
=> ergonomics: remove necessity of into() where possible

z3/src/ast.rs, z3/tests/lib.rs
Realized I missed making these references in #110 
Hope you didn't publish 0.8.0 to crates.io yet, sorry about that.
=> array store: use reference for index and value

z3/src/datatype_builder.rs, z3/src/lib.rs, z3/tests/lib.rs
this makes re-using a particular sort with accessors easier, since it
can just be referenced in the builder:
(psuedocode)
```rust
let some_complex_sort = Sort::set(&ctx, &Sort::set(...));
let datatype_using_that_sort = DatatypeBuilder::new(&ctx, "foo")
.variant("first", vec![("bar", &some_complex_sort)])
.variant("second", vec![("bar", &some_complex_sort), ("count", &Sort::int(&ctx))])
.finish();
```
It is backwards incompatible -- users of the builder would need to add a reference. Also, if the builder is not `finish`-ed immediately, the sort needs a let binding.
=> accept refs for the sort datatype accessor

z3/src/solver.rs
I'm not sure exactly of the purpose of `Z3_MUTEX.lock().unwrap();` so I possibly am not locking properly, but there was a deadlock when calling this function (happened 100% of the time).
=> Fixed get_proof deadlock

z3/src/ast.rs, z3/src/func_decl.rs, z3/src/lib.rs, z3/tests/ops.rs
These are some of the accessors found in the Python and C++ APIs.
Also included is a commit that standardizes some documentation formats.
=> Add accessors for Ast and FuncDecl

z3/src/ast.rs, z3/tests/ops.rs
In the C API, Ast nodes that are `expr` expose the underlyling `FuncDecl`, which allows introspection of the type and name of the node.
One question is about the check whether the `Ast` is an `app` or not.  It seems like by construction they are, but I don't have full confidence in this, and would love a second opinion!
=> Expose Ast::decl() method to return FuncDecl

z3/src/sort.rs
These three functions (present in the C++/Python API) allow one to check if a `Sort` is array-like (`Array` or `Set`), and if so to check the `Sort` of the domain and range.  Non-array-like `Sort`s will return `None` for the latter two functions.
=> Implement Sort::{is_array, array_domain, array_range}

z3/src/ast.rs, z3/tests/lib.rs
Other literal types (Int, Bool, etc) have methods like
`as_bool() -> Option<bool>` or `as_i64() -> Option<i64>` allowing
a literal Ast node to be "unwrapped".  `ast::String` has no such
method, and `to_string` escapes quotes/etc, which makes it challenging
to extract the original stored value.
This introduces an analogous `ast::String::as_string` method, which
returns the original string, unchanged.  `String` constants return
None.
=> Add String::as_string() method

z3/src/tactic.rs, z3/tests/lib.rs
The lifetimes for tactic chains were being applied to the pointer rather than the Tactic's context
=> fix lifetimes for Tactic chaining

z3-sys/build.rs
This tweaks link order when building a static libz3, so that
dangling C++ stdlib symbols can be resolved by the library appearing
aftwerward in linking order.
It fixes a linking failure when trying to use latest Z3 from git,
as it would otherwise fail to resolve C++ stdlib symbols used
by the library.
=> z3-sys/build: fix link order for static lib

z3-sys/src/lib.rs, z3/src/ast.rs, z3/src/datatype_builder.rs, z3/src/lib.rs
This updates crate documentation by adding docstring entries to all
top-level API items.
=> z3: add docstrings for all top-level items

z3/src/sort.rs
I was running into an issue in 0.9 where `DatatypeAccessor::Sort` required an owned `Sort` value. Unfortunately I only had a `&Sort` and it does not implement `Clone`, so I was stuck and decided to make this PR. In the process of making the PR I found #113 which did fix my issue (changed `DatatypeAccessor::Sort` to take a `&Sort`), but I don't like how that API requires extra borrowing. So I decided to continue on with the PR, and maybe the `DatatypeAccessor` API change will be reverted before the next release.
The issue with taking a reference to `Sort` is that a pattern like the following no longer works:
```rust
// Translating my own type system into Z3, specifically structs
let my_name: String = ...;
let my_fields: Vec<(String, IrType)> = ...;
let z3_types: HashMap<IrType, …
```
=> Implement Clone for Sort

z3/src/datatype_builder.rs, z3/src/lib.rs, z3/tests/lib.rs
Reverts the behavior of `DatatypeAccessor::Sort` from holding a `Sort` reference to holding a `Sort` value.
Closes #138
=> Revert #113 (DatatypeAccessor::Sort reference)

z3/src/lib.rs, z3/src/rec_func_decl.rs, z3/tests/lib.rs
This PR adds wrapping to the `z3` crate of `z3-sys`'s `Z3_mk_rec_func_decl` and `Z3_add_rec_def`.
I implemented a new `RecFuncDecl` struct which has an `add_def(args, body)` method, since the `z3-sys` API differentiates between `mk_func_decl` and `mk_rec_func_decl` as far as I can tell.
The `add_def` method has a doc example on how to use the new API and there are two tests (`test_rec_func_def` and `test_rec_func_def_unsat`) in `z3/test/lib.rs`.
I'm not familiar at all with unsafe Rust code and only have a very basic understanding of SMT solvers, so please take a good look and let me know if something's not up to standard.
=> Add interpreted (recursive) functions

z3/src/ast.rs, z3/src/func_decl.rs, z3/src/lib.rs, z3/src/model.rs, z3/src/optimize.rs, z3/src/pattern.rs, z3/src/sort.rs, z3/tests/lib.rs, z3/tests/objectives.rs, z3/tests/semver_tests.rs
I have removed `Dynamic` *parameters* (there are still `Dynamic` return types although I did consider changing them into a `Box<&dyn Ast>`) which added a great deal of unnecessary `into()`, and `from()`s in the user's code and Rust has better methods for dealing with this (mainly `&dyn` traits). Therefore I have modified `Ast` to be usable in a `&dyn` context by removing its `Size` trait which also required removing its `Into<Dynamic<'ctx>>`. This isn't an issue as I we have `from_ast` available in the `Dynamic` struct, and the macro `impl_from_try_into_dynamic`. I don't believe that it is possible to directly have a `From` trait that takes in `&dyn Ast` from my understanding, and testing of Rust although I think we have sufficiently covered the needed use cases anyway.
Minor points
- …
=> Removed Dynamic parameters, and refactored some code

z3/src/tactic.rs, z3/tests/lib.rs
This includes #155, and also handles the nullptr case from `Z3_tactic_apply` when tactics fail.
=> Support tactic failure and `try_for` tactic

z3-sys/README.md, z3-sys/build.rs
This enables the user to choose the path to their z3.h, and doesn't force usage of the system header through wrapper.h.
I.e., by setting the environment variable `Z3_SYS_Z3_HEADER`, the user can determine which z3.h will be used.
Needed this in a project where we did not want to just use the system z3.
=> Add option to choose z3.h location for bindgen

z3-sys/Cargo.toml
Some features of bindgen are not needed when building the library and
lead to unused dependencies (mainly `clap`). This change deactivates all
`bindgen` features except for `runtime` which is required for build to
work.
See also https://github.com/rust-rocksdb/rust-rocksdb/pull/491
=> Removed unneeded bindgen features

z3/src/optimize.rs
=> Remove unused attribute allow(unused_comparisons)

z3/src/ast.rs, z3/src/config.rs, z3/src/context.rs, z3/src/datatype_builder.rs, z3/src/func_decl.rs, z3/src/goal.rs, z3/src/lib.rs, z3/src/model.rs, z3/src/optimize.rs, z3/src/params.rs, z3/src/pattern.rs, z3/src/probe.rs, z3/src/rec_func_decl.rs, z3/src/solver.rs, z3/src/sort.rs, z3/src/tactic.rs, z3/tests/lib.rs, z3/tests/semver_tests.rs
This also fixes an error in _safe_eq
=> Remove #[allow(dead code)] and #[allow(unused variables)]

z3/src/optimize.rs
Closes https://github.com/prove-rs/z3.rs/issues/186
The docs have been updated to show that negative weights are rewards: https://github.com/Z3Prover/z3/blob/master/src/api/z3_optimization.h#L85
=> z3 optimize soft_assert weights can be negative

z3/src/ast.rs
Floating point sorts using incorrect operations for "greater than or equal" and "less than or equal" operations.
=> Correcting operations used for Floating-Point sorts ge and le operations

z3/src/ast.rs, z3/tests/lib.rs
The value for bitvector could be larger than 64 bits, thus the current interface doesn't allow us to create one.
=> feat: add from_str() for BV

z3-sys/src/lib.rs, z3-sys/tests/lib.rs
These are the same as just using `true` and `false`, so just
use those instead.
=> z3-sys: Remove Z3_TRUE / Z3_FALSE consts.

z3/Cargo.toml, z3/src/ast.rs, z3/src/config.rs, z3/src/context.rs, z3/src/datatype_builder.rs, z3/src/func_decl.rs, z3/src/goal.rs, z3/src/lib.rs, z3/src/model.rs, z3/src/optimize.rs, z3/src/params.rs, z3/src/pattern.rs, z3/src/probe.rs, z3/src/rec_func_decl.rs, z3/src/solver.rs, z3/src/sort.rs, z3/src/statistics.rs, z3/src/tactic.rs
The issues with Z3 that caused this to be needed were fixed long
ago, so hopefully this is no longer required.
An earlier version of this patch was developed by <blackbinary@qq.com>.
This replaces the work previously in #143.
=> Remove Z3_MUTEX.

.github/workflows/rust.yml, z3-sys/build.rs
fix #215
Surprisingly, it just needed to use emscripten's sysroot with bindgen. For `wasm32-wasi` target more work is needed, as it doesn't support c++ exceptions yet, but I think `wasm32-unknown-emscripten` is enough for most of use cases (including my use case).
=> Make it buildable for wasm with emscripten

z3/src/goal.rs
A drive-by pr to address a clippy warning. I figured the name of the lifetime was informative, so I just added the allow attribute instead of removing the lifetime/switching to `Goal<'_>`.
One odd thing about the current documentation. For a function like https://docs.rs/z3/latest/z3/struct.Solver.html#method.assert_and_track, I was initially confused that the documentation page referenced an `a` that is not the function argument(which would be `ast`) but instead references the underlying function implementation that is called which has an argument named `a`. This made sense reading the source, but is strange when just reading from the generated docs. I have no suggested change, just an observation of an outsider.
```
/// Assert a constraint `a` into the solver, and track it (in the
/// …
```
=> Add clippy allow Attribute

z3/src/ast.rs
Hello, I would like to suggest a trivial QoL change.
Most functions take a context parameter as `ctx: &'ctx Context`. There are only a couple that take `contex: &'ctx Context`. There is no semantic difference here, however, this does mean that in a few cases an editor will autocomplete a method/function call with a `context` variable name instead of a `ctx`. This is mildly annoying as a user.
This is no doubt a limitation of my autocomplete tooling(the RA extension of VSCode). Despite that, given that the use of `ctx` as an argument name is so prevalent in this crate and its test cases, I am suggesting that the naming be consistent and have done my best to grep for these inconsistencies.
=> rename context args to ctx

z3/src/ast.rs, z3/tests/lib.rs
This PR adds a new `Regexp` struct to `ast` along with the corresponding operations.
=> add regexp support

z3-sys/Cargo.toml, z3/src/datatype_builder.rs, z3/src/goal.rs, z3/src/probe.rs, z3/src/statistics.rs, z3/src/tactic.rs, z3/tests/lib.rs
First of all, thanks _very_ much for this project! It makes it very straightforward to reach for Z3 from Rust.
If you don't mind, this PR makes two changes, both in the interest of appeasing Clippy:
1.  bump dependencies in `z3-sys/Cargo.toml` to ensure a newer `nom` version is used, ameliorating a Clippy's objection `warning: the following packages contain code that will be rejected by a future version of Rust: nom v5.1.2`
2. other small changes in `z3` to appease Clippy & silence warnings
Thanks!
=> Update dependencies and appease Clippy

z3/src/ast.rs, z3/src/lib.rs
I found myself making what I think are unnecessary clones when getting the dynamic versions of an Ast(while still holding onto the typed version of the Ast). I've added an additional `From` impl which I believe to be safe because `Dynamic::as_{bool, int, real}` do the inverse of this. https://github.com/prove-rs/z3.rs/blob/ee521b74bbe0e76113b2399e1a4640b3d6995181/z3/src/ast.rs#L1626-L1655
I also fixed a small copy-paste error.
=> ref ast conversion into Dynamic

z3-sys/src/lib.rs, z3/src/func_entry.rs, z3/src/func_interp.rs, z3/src/lib.rs, z3/src/model.rs, z3/tests/lib.rs
I am interested in getting the interpretation that a model has of a function by exposing `FuncInterp` to the high level bindings.
I've heavily drawn from the other Z3 bindings in the public facing methods I've implemented while following the same general format that other structs have with the `wrap` and `Drop` implementations.
Some/most bindings overload the `get_const_interp` method to handle both `Ast`'s and `FuncDecl`'s which I haven't done.
I'll note that `get_func_interp` is particularly complex compared to most of the methods implemented, though it is almost entirely drawn from other implementations and I've free-handed the use of `Z3_mk_ast_vector` in `add_entry`. These probably require additional attention.
I'll be looking to add some rough documentation/tests.
Related to #213
=> implementing FuncInterp & FuncEntry

.github/workflows/rust.yml, z3-sys/build.rs, z3-sys/tests/lib.rs, z3/tests/lib.rs, z3/tests/objectives.rs, z3/tests/ops.rs, z3/tests/semver_tests.rs
With #228 and previously #217, a couple of pr's have been accepted to address clippy suggestions. Given this, it seems reasonable to move clippy into the github actions workflow.
This pr:
- Adds an additional, parallel job to the workflow to run clippy across the whole workspace.
- Picks some low hanging ci performance fruit by using `CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse` and not statically building `z3` twice(As I later found mentioned in https://github.com/prove-rs/z3.rs/pull/207#issuecomment-1196265484).
- Fixes the last of clippy's suggestions in various build/test files.
Depending on the status of #207, it would be faster to run clippy without `static-link-z3`. Sometimes people also move `cargo fmt` into the ci.
=> Move clippy into CI

z3/src/solver.rs, z3/tests/lib.rs
Z3 has no native way to copy a solver, commonly useful for BFS style tree traversals of contexts of execution.  Sometimes solver push/pop suffices and sometimes you just need to copy.  This code uses the [same operations Leonardo suggested](https://stackoverflow.com/questions/16516337/copying-z3-solver) on the topic to cope with Z3's lack.
=> Expensive copy of a solver

z3/src/model.rs, z3/tests/lib.rs
One nice abstraction that the python bindings implement is to be able to iterate over a `Model`. One can then use the features added in #221 to get the interpretations that the `Model` assigns for these declarations.
If this is worth adding, the implementation comes from https://z3prover.github.io/api/html/classz3py_1_1_model_ref.html#a7890b7c9bc70cf2a26a343c22d2c8367 where they hook into Python's `__len__` and `__getitem__` to extract all consts and funcs from a model when using a for loop. I think the only difference here is that for Rust we need to manage a struct that does the iteration, here `ModelIter`(akin to https://doc.rust-lang.org/std/slice/struct.Iter.html) which contains the current index into the model and the total length.
The testcase is related to #221.
=> Implement Iterator over a Model

z3-sys/src/lib.rs, z3/src/optimize.rs, z3/src/solver.rs, z3/tests/lib.rs
I am interested in pushing through #194.
The changes I made are:
- Loosening the input type to be `Into<Vec<u8>>` which is the most general type CString expects. This allows one to pass a &str to this function as shown in the tests. (Comment in https://github.com/prove-rs/z3.rs/pull/194#discussion_r927060804)
- The inner unsafe code is reworked to the current style used in the library with `Self::wrap` for construction.
- Renamed the function argument in `Z3_solver_from_string` to be `c_str` which matches the cpp api https://github.com/Z3Prover/z3/blob/a0f3727e90c4446ba2c1fa7e4392637587ad9632/src/api/api_solver.cpp#L358-L369 and makes more sense to me
=> Z3 from string

z3-sys/src/lib.rs
`Z3_parse_smtlib2_string` and `Z3_parse_smtlib2_file` are marked as returning a `Z3_ast`, while they should be returning a `Z3_ast_vector` (https://z3prover.github.io/api/html/group__capi.html#ga7905ebec9289b9fe5debcad965f6267e). This (tiny) PR fixes the problem.
=> z3-sys: Fix return type of Z3_parse_smtlib2_string and Z3_parse_smtlib2_file

z3/tests/lib.rs
In playing around with enabling the error_handler, I noticed that the tests for #226 were actually incorrect but there was no error checking so this was just ignored.(Whoops, my bad)
Maybe the api should be changed to avoid this? Something akin to https://github.com/prove-rs/z3.rs/blob/691ac9782f361969e87ac745a3d9a6816593741a/z3/src/tactic.rs#L207-L211. In general, I think there should be a better story for integrating with Z3's errors.
=> Fix smt based tests

z3/src/lib.rs, z3/src/rec_func_decl.rs, z3/tests/lib.rs
Given that both structs(`FuncDecl` and `RecFuncDecl`) provide the same functionality modulo `add_def`, it's kind of unfortunate that the signatures for `apply` uses a different type for the `args`.
https://github.com/prove-rs/z3.rs/blob/691ac9782f361969e87ac745a3d9a6816593741a/z3/src/func_decl.rs#L62
vs 
https://github.com/prove-rs/z3.rs/blob/691ac9782f361969e87ac745a3d9a6816593741a/z3/src/rec_func_decl.rs#L117
In this case it's slightly better to pass a `&dyn Ast` instead of a `&Dynamic` because the latter may require creating a temporary that is only used by reference when creating an array to pass as `args`(which can make some code a bit awkward).
I've made this short change in the first commit and removed the `into` conversions from the tests which are now ambiguous.
I've also thought …
=> Aligning `apply` methods of FuncDecl and RecFuncDecl

z3/src/context.rs, z3/src/lib.rs, z3/src/params.rs, z3/tests/lib.rs
=> Add bindings for global params

z3/src/optimize.rs
With the error_handler turned off, I had the following warning suppressed when using `Optimize::maximize`: `Error: Objective must be bit-vector, integer or real`.
I am suggesting that an assertion or result type is added to help catch this. Also holds true for minimize.
=> Check Kind for optimize maximize

z3/src/ast.rs, z3/tests/ops.rs
Hello!
Sometimes when using z3 I follow the pattern of constructing `Bool<'_>` values in a map(Like making a list of variables from a list of names or arguments).
```rust
let output_assertions = circuit
.outputs
.iter()
.map(|o| {
let o1 = nodes0.get(o).unwrap();
let o2 = nodes1.get(o).unwrap();
o1._eq(o2).not()
})
.collect::<Vec<Bool>>();
```
The problem is that variable length operations like `Bool::or` expect a `&[&Self]` which is an array of references, not values. 
Note that because I'm constructing these as values in a closure, I cannot collect a vector of references because the underlying values would be dropped.
I end up writing code like the following:
```rust
solver.assert(&Bool::or(
ctx,
output_assertions.iter().collect::<Vec<_>>().as_slice(),
));
```
It appears to me that this …
=> Use Borrow in varop arrays

z3/src/ast.rs
- Distinct currently takes `&[&Self]` for which I would like to do a similar api relaxing like in #246.
- With the new Rust version, there is a minor clippy change.
- Python has this nice `is_const_array(a)` function which I would like to propose here.
=> is_const_array and Distinct with &[impl Borrow<Self>]

.github/workflows/rust.yml
This is faster than having it do a build of Z3 as it does now and by running it on macOS against the brew installed Z3, it is going to be a more recent version of Z3 than what the system Z3 on Linux would be.
=> ci: Run clippy on macOS against brew z3.

.github/workflows/rust.yml
Instead of building the lib and then doing the tests, just do the tests. Otherwise, we end up building the lib twice.
This also:
* No longer uses `-vv` for very verbose output.
* Uses `--workspace` instead of `--all`.
=> Improve CI speed.

.github/workflows/rust.yml, z3/Cargo.toml, z3/src/ast.rs, z3/src/lib.rs, z3/src/optimize.rs, z3/tests/lib.rs
=> Always use `num`, remove `arbitrary-size-numeral` feature.

z3/src/ast.rs, z3/tests/lib.rs
Fixes https://github.com/Z3Prover/z3/issues/6958
=> Implement `ast::Float::as_f64`

.github/workflows/rust.yml
This is in addition to running them against it on Linux.
=> ci: Run tests against homebrew Z3 on macOS.

.github/workflows/rust.yml, z3-sys/Cargo.toml, z3-sys/README.md, z3-sys/build.rs, z3/Cargo.toml, z3/README.md
This renames the `static-link-z3` build feature to `bundled` but leaves a bit around for now to maintain compatibility.
It also improves the README's discussion a little bit to mention `vcpkg`.
=> Rename `static-link-z3` to `bundled`.

z3/src/solver.rs, z3/tests/lib.rs
Hi, I was unable to find a function that converts the solver to SMT-LIB2 format.
I wrote one based on the functions in the python/C++ APIs below.
```
def to_smt2(self):
"""return SMTLIB2 formatted benchmark for solver's assertions"""
es = self.assertionsassertions()
sz = len(es)
sz1 = sz
if sz1 > 0:
sz1 -= 1
v = (Ast * sz1)()
for i in range(sz1):
v[i] = es[i].as_ast()
if sz > 0:
e = es[sz1].as_ast()
else:
e = BoolVal(True, self.ctxctx).as_ast()
return Z3_benchmark_to_smtlib_string(
self.ctxctx.ref(), "benchmark generated from python API", "", "unknown", "", sz1, v, e,
)
std::string to_smt2(char const* status = "unknown") {
array<Z3_ast> es(assertions());
Z3_ast const* fmls = es.ptr();
Z3_ast fml = 0;
unsigned sz = es.size();
if (sz > 0) {
--sz;
fml = fmls[sz];
}
else {
fml = …
```
=> Expose API to convert solver into SMT-LIB2 format

z3/src/solver.rs
The python bindings have `solver += Bool` which seems like some handy sugar.
I was also experimenting with overloading the operation with both `&Bool` and `Bool` which seems somewhat convenient but that isn't something I feel too strongly about.
Tested via a Doctest to raise awareness
=> Implement += for Solver

z3-sys/src/lib.rs
This adds support for `Z3_mk_re_allchars`, `Z3_mk_re_diff`, and `Z3_mk_re_power`.
=> z3-sys: Add more recent regular expression func bindings.

z3-sys/Cargo.toml, z3-sys/build.rs
This helps find the lib and includes more accurately than not using it.
This builds on previous work by @poscat0x04 and @wtdcode.
=> z3-sys: Use `pkg-config` when using system libs.

z3/src/sort.rs
Fixes the lifetimes on `array_domain` and `array_range` functions on `Sort`. The lifetime should be `'ctx`, not the lifetime of `self`.
=> sort: fix array_range and array_domain lifetimes

z3/src/ast.rs
This is an alternative to #191, fixing #190. I simply added new functions to the existing `Dynamic` type.
=> add new_const and fresh_const functions to Dynamic

z3/src/optimize.rs
This allows configuring `Optimize` instances. I'm using this to enable the 'box' priority mode, but that'll require additional API changes.
(Other Z3 bindings return an "objective handle" and allow fetching lower and upper bounds. These handles are index-based though and are not reference counted, so I'm not sure about the best Rust API equivalent yet.)
=> Optimize: Add parameter configuration API

z3/src/lib.rs, z3/src/version.rs, z3/tests/lib.rs
I like to use this to check that the right Z3 library got linked, so it would be good to have it accessible from the high-level interface.
=> Expose Z3_get_version in the high-level interface

.github/workflows/rust.yml
An update to emscripten brought a newer compiler and that found a longstanding bug in Z3 that broke compilation.
For now, use a slightly older version until a new version of Z3 (after 4.13.0) is released with the fix.
See https://github.com/Z3Prover/z3/pull/7235 for the Z3 fix.
=> ci: Use slightly older emscripten for now

z3-sys/build.rs
This also changes a test to be less specific about the exact answer since it varies between versions of Z3.
=> Update bundled Z3 to z3 4.12.3.

z3/src/context.rs, z3/src/sort.rs
This would be useful to use functions from the raw bindings that aren't exposed in the high-level bindings yet. Since the raw bindings are `unsafe`, it should be fine to give access to the `Z3_context` and `Z3_sort`.
Closes #290.
=> Expose underlying Z3_context and Z3_sort

z3-sys/src/lib.rs, z3/src/ast.rs, z3/tests/lib.rs
Fixes #272
(First two commits) My attempt at adding the new regular expression operations: `power`, `allchar`, and `diff`. I also noticed that `option` was exposed but not implemented so I've added that as well.
(Third commit) I was looking to test my inclusions to the code base but I realized that I'm not sure about the semantics of regular expressions in Z3? I ran into some weird behavior I don't understand so I just added a simple test from https://z3prover.github.io/api/html/z3py_8py_source.html#l11172 to get some advice. `test_regex_union` works as expected, checking that `(a|b)` matches with `a` and `b` but not `c`. However, I found that I get `SatResult::Sat` in more cases than I expect like in `test_regex_union2` which just checks that `c` matches with `(a|b)`. I would expect to …
=> Support for more regular expression operations

z3/src/optimize.rs, z3/tests/lib.rs
I noticed these are missing from `Optimize` and would have some use for them.
=> Z3 Optimize: add `assert_and_track` and `get_unsat_core`

z3/src/ast.rs, z3/tests/lib.rs, z3/tests/ops.rs
It's a bit difficult to work with `Real` (in `z3`, not `z3-sys`) since the only provided way to get a value out at the end is `Real::as_real(&self) -> Option<(i64, i64)>`, which really only works for rational numbers. In this PR I've added two new functions to help:
- `Real::approx(&self, precision: usize) -> ::std::string::String`, which gives a string approximation of the real value up to `precision` correct digits after the decimal (via `Z3_get_numeral_decimal_string`).
- `Real::approx_f64(&self) -> f64`, which is just a convenience wrapper for `self.approx(17).parse().unwrap()` to get a full-precision `f64` approximation of the real number.
I also noticed that `tests/objectives.rs`, `tests/ops.rs`, and `tests/semver_tests.rs` weren't actually having their tests executed since they …
=> Real approx functions

z3/src/solver.rs, z3/tests/lib.rs
Add consequences, allowing you to derive implied propositions from a set of assumed propositions.
I'm not an expert rust user, feel free to point out any improvements possible.
=> Support consequences API (#302)

z3/src/ast.rs
This commit adds the binding to create lambda consts and a way to select from the lambdas.
=> Add high-level binding to create lambda consts

z3-sys/src/lib.rs, z3/src/ast.rs, z3/src/sort.rs
This commit exposes the sequence sort in the high level z3 binding and adds the `Z3_mk_seq_nth()` low level binding.
=> Expose sequence sort and AST

z3/src/ast.rs, z3/tests/lib.rs
Adds bindings for `atleast` and `atmost`. These functions are generic over `IntoIterator<Item = &'a Bool<'ctx>>` so that calling code can potentially reduce the amount of allocations since we always have to collect the input of `Bool` into an  `Z3_AST` array.
Some simple tests for both functions have also been added.
=> feat: atmost and atleast

z3/src/ast.rs
This PR exposes the `Z3_mk_fpa_to_ieee_bv()` API which is useful for interpreter memory model.
=> Add binding for FPA to IEEE-754 bit-vector

z3/src/model.rs, z3/tests/lib.rs
Currently, iterating over a Model creates `FuncDecls` that reference the lifetime of the reference of the model that they come from, rather than the lifetime of context it contains.
This means that it is impossible to use those `FuncDecls` after the model is dropped, even when the context is still around. From looking at the code, this just seems like a bug, but let me know if this is intentional.
This PR adjusts the lifetimes of `ModelIter` to also explicitly include the lifetime of the model reference. This way it can return `FuncDecl` that properly reference the lifetime of the context.
=> Adjust lifetimes on `ModelIter` to make them more permissive

z3/src/ast.rs
=> Add high-level binding for quantifier creation with additional attributes

z3-sys/Cargo.toml
This commit upgrades the `cmake` and `pkg-config` packages. Additionally, it upgrades the z3 submodule to the current version `z3-4.15.1`
=> Upgrade dependencies and z3 version

z3/src/lib.rs
I'm working on writing Python bindings for some code that I have that uses z3.rs. I would like my bindings to be able to work seamlessly with python's z3 library (producing terms and assertions to be used in python's handle to a solver for instance). I'm writing an opinionated API around the assumption that Python is always "driving" and that we are ALWAYS using Python's global Z3 context (allocated once on first use, never dropped or moved).
Pyo3 has the requirement that any Rust type passing into Python cannot have a lifetime other than `'static`, and all my structs have the z3.rs `'ctx` lifetime.
I'm working around this by pulling in a pointer to Python's global `Z3_Context` and storing it in a `thread_local` `RefCell<Z3_Context>`. I have a second `thread_local` with a `'static` …
=> Make `z3_ctx` `pub`

z3/src/tactic.rs
Fix for #338 ... Throwing a panic to let the user know they provided an invalid tactic name when trying to create a new tactic. Current behavior is to use the ptr returned from Z3 which could be a null pointer resulting in a SIGSEGV which may be more difficult to understand than the panic from the Rust side.
=> Panic through rust if provided an invalid tactic str to prevent SIGSEGV

.github/workflows/release-plz.yml, README.md, z3-sys/README.md, z3/README.md
See https://github.com/release-plz/release-plz for details.
TLDR is this allows for using github actions to automatically:
* Determine when/what semantic versioning updates are justified by changes to `master` and make a PR bumping every crate to its new version
* Make tags and github releases upon "release PR" acceptance
* Make crates.io releases upon "release PR" acceptance
* Maintain unmerged release PRs; maintainers are not pushed to make a release every `master` commit under this system
In this PR, I've run the `release-plz init` standard setup and done what I could on the github-side to configure this.
In order for this to actually work, some things need to be set up by @waywardmonkeys:
* I've configured `release-plz` to use "Trusted Publishing" on crates.io. See …
=> feat: Use release-plz for painless releases

z3/README.md
Hi there!
I've noticed a typo in the main `z3` readme concerning installation options (it said there were 3 instead of 4 installation options). I've fixed that and taken the opportunity to expand the section a bit.
Thanks a lot for the recent flurry of work, it's great to see life in this project!
=> docs: Better documentation of z3 installation options

.github/workflows/rust.yml, z3-sys/Cargo.toml
A couple CI changes to reduce the pain of development:
* `vcpkg` builds are updated to v7 of the `vcpkg` action, and are correctly cached now. They now run in a couple minutes instead of 40 minutes.
* Bundled builds on linux and macos use sccache and complete in 3 minutes instead of 7 and 15. Windows will take more work and still takes 40 minutes. I've been unable to get sccache to fully work with the emscripten build so far. Just caching the rust parts gets it down from 50 minutes to 38 minutes, but I suspect more is possible. However I'm not an expert in emscripten or sccache so it's probably not the best use of my time.
* Bundled builds (linux, macos, windows, wasm) only run on tags and on master now. Most contributions to this library are not ones that will break things at link time, …
=> ci: github action updates and caching

z3/src/ast.rs, z3/tests/lib.rs
Follow-up to #346 
The old definition of `translate` had a subtle bug in which the lifetime of the destination context was constrained to be at least as narrow as the source context (when they should be completely independent).
This is because `translate` was defined in `impl<'ctx> Ast<'ctx>`, so it could only refer to the implementing type as `Self`, which implicitly has a `'ctx` lifetime.
Correctly implementing this function requires that it returns the same concrete type, but with a different lifetime. This is fixed by moving the definition out of the `Ast` trait and into an `impl` block directly on the implementing type.
=> fix: Make translate 'dst lifetime independent of 'ctx

z3-sys/CHANGELOG.md, z3-sys/Cargo.toml, z3/CHANGELOG.md, z3/Cargo.toml
* `z3-sys`: 0.9.2 -> 0.9.3 (✓ API compatible changes)
* `z3`: 0.13.1 -> 0.13.2 (✓ API compatible changes)
<details><summary><i><b>Changelog</b></i></summary><p>
<blockquote>
- narrow build flag impact of wasm fix ([#362](https://github.com/prove-rs/z3.rs/pull/362)) (by @toolCHAINZ) - #362
- github action updates and caching ([#368](https://github.com/prove-rs/z3.rs/pull/368)) (by @toolCHAINZ) - #368
* @toolCHAINZ
</blockquote>
<blockquote>
- Make translate 'dst lifetime independent of 'ctx ([#365](https://github.com/prove-rs/z3.rs/pull/365)) (by @toolCHAINZ) - #365
- Better documentation of z3 installation options ([#364](https://github.com/prove-rs/z3.rs/pull/364)) (by @lmondada) - #364
* @toolCHAINZ
* @lmondada
</blockquote>
</p></details>
---
This PR was generated with …
=> chore: release

.github/workflows/rust.yml
`github.repository_owner` did not work the way I thought
=> ci: only run normal build and vcpkg on forks (fix)

z3/src/ast.rs
If we have a biginteger type, it is usually implemented as `Vec<u64>` internally. To create a `BV` from such instance, converting to string and then letting Z3 parse it is a bad style for me. The `from_bits` method can avoid such printing and parsing.
=> feat: add BV::from_bits 

z3/src/ast.rs
Follow-up to @Evian-Zhang's #398.
Playing around with this API more, I found that `Z3_mk_bv_numeral` returns `null` if an empty bit slice is provided. Since this call does seem to be fallible, it's preferable to wrap this in `Option` like the  other fallible BV APIs (e.g. `from_str`).
=> fix: make BV::from_bits return Option

z3/src/ast.rs, z3/src/context.rs, z3/src/datatype_builder.rs, z3/src/func_decl.rs, z3/src/func_entry.rs, z3/src/func_interp.rs, z3/src/goal.rs, z3/src/lib.rs, z3/src/model.rs, z3/src/ops.rs, z3/src/optimize.rs, z3/src/params.rs, z3/src/pattern.rs, z3/src/probe.rs, z3/src/rec_func_decl.rs, z3/src/solver.rs, z3/src/sort.rs, z3/src/statistics.rs, z3/src/symbol.rs, z3/src/tactic.rs, z3/tests/lib.rs, z3/tests/ops.rs
This PR makes `Context` internally refcounted on the Rust side with an `Rc` around a `pub(crate)` wrapper implementing `Drop`. This has a couple effects:
* All other z3 types (e.g. all `Ast`s, `Solver`s, etc) _own_ their (refcounted) `Context` handle, removing almost all instances of the `'ctx` lifetime (with the exception of those associated with the `ContextHandle` type).
* The `Context` is refcounted on the rust side any time an `Ast`/`Solver`/etc is cloned and decremented any time it is dropped.
Simple consuming code will mostly be unchanged due the compiler eliding lifetimes in the old version. Removing the occasional lifetime argument was the only change required for the existing test suite.
This is a *BREAKING* change: consuming code with types wrapping `z3.rs` types must be …
=> changed!: refcount z3 context

z3/src/context.rs
Most `z3` Rust code has the following boilerplate to make a context:
```rust
let cfg = Config::default();
let ctx = Context::new(&cfg);
```
To streamline this a bit, this just defines `Default` for `Context` to use `Config::default()`.
=> feat: impl Default for Context

z3/tests/lib.rs
This PR adds constructors for two IEEE-754 rounding modes in the `Float<'ctx>` API.
- `round_towards_nearest_away(ctx: &Context) -> Float<'ctx>`  
Creates a rounding mode corresponding to "round to nearest, ties away from zero".
- `round_towards_nearest_even(ctx: &Context) -> Float<'ctx>`  
Creates a rounding mode corresponding to "round to nearest, ties to even".
These functions wrap the Z3 FFI:
- `Z3_mk_fpa_round_nearest_ties_to_away`
- `Z3_mk_fpa_round_nearest_ties_to_even`
=> chore: add unit tests for rounding modes

z3-sys/src/lib.rs
This PR removes z3-sys' dependency on std.
This gives users of z3-sys the choice to pull in std or not, which is currently not possible.
=> feat(z3-sys): do not depend on std

z3/src/ast/mod.rs, z3/tests/lib.rs
=> fix: Ast::ne -> Bool is now defined and preferred over PartialEq::ne

z3/Cargo.toml, z3/src/ast/regexp.rs
This PR adds features to the z3 crate which selectively enables high-level APIs based on their usage of the low-level Z3 API.
Specifically, a few APIs that were added in 4.8.13, 4.8.14, and 4.8.15 (all after the version shipped with ubuntu, 4.8.12) are now gated behind features.
This PR makes `z3_4_8_15` a default feature, so the APIs will not be disables unless a user opts out through `default-features = false`. This is necessary to build on ubuntu 24.04 LTS without linking path nonsense.
=> feat: gate newer Z3 APIs behind features
