z3/src/sort.rs

From discussions in #8, this closes a gap in the API, letting us construct integer bitvectors constants from a bitvector sort.
I'm not sure whether I need to increment the reference count, but that wasn't done after other calls to `Z3_mk_[unsigned_]int64`, so I assume no.

Add functions to construct an integer Ast from a Sort

---

z3/src/func_decl.rs

fix FuncDecl

---

z3/src/ast.rs
z3/src/context.rs
z3/src/func_decl.rs

Forall const

---

z3/src/context.rs
z3/src/func_decl.rs
z3/src/sort.rs

Enumeration sort

---

z3/src/ast.rs
z3/tests/lib.rs

adding comparison operators on reals

---

z3/Cargo.toml
z3/src/ast.rs
z3/src/lib.rs
z3/tests/lib.rs

implemented functions for building arbitrary size int and reals

---

z3/src/ast.rs
z3/src/lib.rs
z3/src/optimize.rs
z3/src/solver.rs
z3/src/sort.rs
z3/tests/lib.rs
z3/tests/semver_tests.rs

Add SatResult type

---

z3/src/ast.rs

Fix doctest of exists_const

---

z3/src/func_decl.rs
z3/src/lib.rs
z3/src/model.rs
z3/src/optimize.rs
z3/src/params.rs
z3/src/solver.rs
z3/src/sort.rs

This PR adds `Debug` implementation to all types. Corresponding to #66.

Feat: Add Debug implementation to all types

---

.gitmodules
.travis.yml
z3-sys/Cargo.toml
z3-sys/build.rs
z3-sys/src/generated/decl_kind.rs
z3/Cargo.toml
z3/src/ast.rs
z3/src/solver.rs
z3/tests/lib.rs

Please take a look @waywardmonkeys :)

Add `Solver::get_unsat_core`, a feature for static linking, and some other small fixups

---

.github/workflows/rust.yml
z3-sys/build.rs

We were previously only testing on Linux.
I expect this to take a few force pushes to get green >.<

ci: Also test static-linking builds on macOS and Windows

---

z3-sys/build.rs

Enable parallel build of static lib on Windows

---

z3/src/model.rs
z3/tests/lib.rs

This pull request added `Model::translate` using `Z3_model_translate`. The test was also added.

Feature: add translate on model

---

z3/src/datatype_builder.rs
z3/src/lib.rs
z3/tests/lib.rs

DatatypeBuilder changes to support recursive datatypes

---

z3/src/datatype_builder.rs

We previously fixed this issue in 66c1f8a (a.k.a. PR #73) but it was
reintroduced when we refactored the datatype code to allow for mutually
recursive datatypes.
I investigated setting up ASan in our CI, but we get so many failures running
RUSTFLATS="-Z sanitizer=address" cargo test --all-features
that I gave up.

Stop leaking `Z3_constructor`s (again)

---

z3/src/ast.rs
z3/tests/ops.rs

To traverse the Ast, one needs access to the (possibly empty) children of each
node.  This commit introduces:
1. num_children(&self) -> usize: The number of children, possibly 0.
2. nth_child(&self, idx) -> Dynamic: The nth child as a Dyanmic node.
3. children(&self) -> Vec<Dynamic>: The children as a Vec.
Fixes #106

Add Ast methods for accessing child nodes

---

z3/src/ast.rs
z3/tests/lib.rs

This should be member. Also looks like element comes first for this function: https://docs.rs/z3-sys/0.6.3/z3_sys/fn.Z3_mk_set_member.html

correct bug in membership: Z3_mk_set_add -> Z3_mk_set_member

---

z3/src/ast.rs
z3/tests/lib.rs

Check that the range of the array is boolean & allow the conversion. Since a set is just an array with a boolean range, it would be possible to convert a boolean-ranged, array-sorted node into a set-sorted one.

ast: support converting Dynamic back into Set

---

z3/src/optimize.rs
z3/src/solver.rs
z3/tests/objectives.rs
z3/tests/ops.rs

I've added a testcase that asserts on both.
It's a bit large, let me know if I should pull it out into a separate file / come up with something a bit simpler.

Optimize: add soft asserts and ability to get objective

---

z3/src/sort.rs
z3/tests/lib.rs

As title says. Pretty small change to add some functions I needed.

Added functions to get significand and exponent of floating point sorts

---

z3/src/goal.rs
z3/src/lib.rs
z3/src/tactic.rs
z3/tests/lib.rs

This pull request is in reference to #124. It adds an implementation of goal and tactic containing the most useful methods along with tests for those methods.

Implement Tactic and goal

---

z3/src/ast.rs
z3/src/goal.rs
z3/src/lib.rs
z3/src/sort.rs
z3/src/tactic.rs
z3/tests/lib.rs

this is adds a method "_safe_eq" that returns a `Result` when comparing two ast nodes and checks that they have the same `SortKind`.

add safe_eq

---

z3/src/ast.rs
z3/tests/lib.rs

Fix bug with Set::del

---

z3/src/solver.rs

This simply adds a small wrapper for Z3_mk_solver_for_logic, similar to
the one for Z3_mk_solver (though it returns an Option<Solver>, since the
input may be invalid).
(Note that Z3_mk_solver_for_logic returns a null pointer on invalid
input, contrary to its comment, which suggests that it returns a default
solver.)

expose Z3_mk_solver_for_logic

---

.github/workflows/rust.yml
z3/tests/lib.rs

Fixes to CI

---

z3/src/optimize.rs

This makes it consistent with the Solver impl.

patch: add get_context method to Optimize

---

z3/src/goal.rs
z3/src/tactic.rs

Remove the unsound Goal::new_from_z3_type

---

z3-sys/src/generated.rs
z3/src/datatype_builder.rs
z3/src/goal.rs
z3/src/optimize.rs
z3/src/solver.rs
z3/tests/semver_tests.rs

This does some things that @SeeSpring has done before (but I did independently and then noticed in some of their draft PRs).

Fix warnings

---

z3/src/ast.rs
z3/src/func_decl.rs
z3/src/goal.rs
z3/src/model.rs
z3/src/ops.rs
z3/src/optimize.rs
z3/src/rec_func_decl.rs
z3/src/solver.rs

Based on #178 to avoid merge conflicts. I can separate it if you want

Fix clippy errors

---

z3/src/solver.rs

I had made a suggestion to @TomMD that with #230 being merged I'll resubmit here.
If `get_assertions` is factored out from `Clone`, the library can both supply a safe api for this functionality and implement `Clone` in a way that imo is cleaner and reuses functionality that is already provided.

factor out get_assertions from Clone

---

z3/src/ast.rs
z3/tests/ops.rs

Closes #220 
I found a relevant z3 issue where they mention the change in behavior which I think is the cause of this bug? https://github.com/Z3Prover/z3/issues/5623

Have Int::power return Real

---

.github/workflows/rust.yml
z3-sys/build.rs

cc: @TheVeryDarkness 
Seeing if we can enable this now...

ci: Enable vcpkg build on macOS and Linux

---

z3-sys/build.rs

This seems to fix debug windows builds on my machine

Update bundled z3 (fix windows debug builds)

---

.github/workflows/rust.yml

Bumped the version of z3 to the 4.13.2 tag and updated emscripten.

Update Z3 to 4.13.2 and update emscripten to `latest`

---

z3-sys/README.md
z3-sys/build.rs
z3/README.md

feat: Add Z3_LIBRARY_PATH_OVERRIDE
